configVersion: 3

redisUri: redis://localhost:6379
redisChannel: seers-jsq:main

joinMessagePrefix: "<gray>[</gray><green>+</green><gray>]</gray> "
joinMessageSuffix: " <gray>({next_server})</gray>"
joinMessages:
- "%jsq_player% <yellow>showed up. The party can finally start!</yellow>"
- "%jsq_player% <yellow>arrived. We're back in business!</yellow>"
- "%jsq_player% <yellow>connected. Better late than never</yellow>"
- "%jsq_player% <yellow>is here. Great.</yellow>"
- "%jsq_player% <yellow>is here. Let's goooo</yellow>"
- "%jsq_player% <yellow>is here. Brace yourselves!</yellow>"
- "%jsq_player% <yellow>just joined. Everybody wave!</yellow>"
- "%jsq_player% <yellow>is here! Yes! Gosh</yellow> %jsq_player% <yellow>is great</yellow>"
- "%jsq_player% <yellow>logged in. How long 'til they fall in lava?</yellow>"

switchMessagePrefix: "<gray>[</gray><light_purple>></light_purple><gray>]</gray> %jsq_player% <yellow>switched from</yellow> <gray>{previous_server}</gray> <yellow>to</yellow> <gray>{next_server}</gray>"
switchMessageSuffix: ""
switchMessages:
- ""

quitMessagePrefix: "<gray>[</gray><red>-</red><gray>]</gray> "
quitMessageSuffix: ""
quitMessages:
- "%jsq_player% <yellow>has left. The game just got 10% easier</yellow>"
- "%jsq_player% <yellow>disconnected. Did they rage quit?..</yellow>"
- "%jsq_player% <yellow>rage quit</yellow>"
- "%jsq_player% <yellow>has left. Finally, some peace and quiet</yellow>"
- "%jsq_player% <yellow>bailed. Guess they had better things to do</yellow>"
- "%jsq_player% <yellow>disconnected. We’re doomed without them... or not</yellow>"
- "%jsq_player% <yellow>logged out. Time for the real players to shine</yellow>"
- "%jsq_player% <yellow>bailed. Did someone forget to feed them?</yellow>"
- "%jsq_player% <yellow>is gone. Panic!</yellow>"
